name: mono_app
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  carousel_slider: ^4.1.1
  connectivity_plus: ^3.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  expandable_page_view: ^1.0.17
  flash: ^2.0.3+3
  flutter_launcher_icons: ^0.10.0
  fresh_dio: ^0.3.2
  get_it: ^7.2.0
  injectable: ^2.1.0
  intl: ^0.17.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  shimmer: ^2.0.0
  sprintf: ^7.0.0
  sliding_up_panel: ^2.0.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  loader_overlay: ^2.3.2
  flutter_modular: ^6.3.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  change_app_package_name: ^1.1.0
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
